### ISSUE TITLE
What do the various DBImageColorPickerBackgroundType mean?

### ISSUE THREAD

**Issue by faceleg** [d0ping/DBImageColorPicker#2]
How do they change the extracted colours?

**Comment by d0ping** [comment]
Just change the image property on DBImageColorPicker instance. Color properties updated automatically.

**Comment by faceleg** [comment]
Hmm I mean: how do they affect the resulting colours? I'm confused

**Comment by faceleg** [comment]
As in, what situations would be best suited to using the three enum values?

**Comment by d0ping** [comment]
Oh, I understand about what you ask. DBImageColorPickerBackgroundType affects how the background color (and additional colors) will be obtained. 
- DBImageColorPickerBackgroundTypeDefault - allows to get average color;
- DBImageColorPickerBackgroundTypeHeaderSide - allows to get the average color of the upper right part of the image (10% of the image);
- DBImageColorPickerBackgroundTypeFooterSide - allows to get the average color of the lower right part of the image (10% of the image).
  Different types of backgroundColor needed because it is not always the average color (default) looks so good.

**Comment by d0ping** [comment]
On the example app uses DBImageColorPickerBackgroundTypeFooterSide type.

**Comment by faceleg** [comment]
This is great information - please consider adding it to the readme!

**Comment by d0ping** [comment]
I agree. It was necessary to add this information to readme. I'll do it in the next version.
Thank you for feedback.
